name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
          targets: i686-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update
      - run: sudo apt-get install --yes z3
      - run: ./scripts/verify.sh

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo +1.85.0 check --all-targets --all-features
